export default {
  title: 'Tempo',
  units: [
    'nanosecond',
    'microsecond',
    'millisecond',
    'second',
    'minute',
    'hour',
    'day',
    'week',
    'month',
    'year',
    'calendar_year',
    'decade',
    'century',
  ],
  labels: {
    nanosecond: 'Nanosecondo',
    microsecond: 'Microsecondo',
    millisecond: 'Millisecondo',
    second: 'Secondo',
    minute: 'Minuto',
    hour: 'Ora',
    day: 'Giorno',
    week: 'Settimana',
    month: 'Mese',
    year: 'Anno',
    calendar_year: 'Anno civile',
    decade: 'Decade',
    century: 'Secolo',
  },
};
